server:
  port: 8080
spring:
  cloud:
    config:
      server:
        git:
          default-label: eureka
          uri: https://github.com/JuanPatinoGomez/microservicios-tutorial
          search-paths: config-data
  application:
    name: config-service

